In [3]:
import pandas as pd

df = pd.read_parquet("../data/raw/swebench_verified.parquet")

df.head()

,repo,instance_id,base_commit,patch,test_patch,problem_statement,hints_text,created_at,version,FAIL_TO_PASS,PASS_TO_PASS,environment_setup_commit,difficulty
0,astropy/astropy,astropy__astropy-12907,d16bfe05a744909de4b27f5875fe0d4ed41ce607,diff --git a/astropy/modeling/separable.py b/a...,diff --git a/astropy/modeling/tests/test_separ...,Modeling's `separability_matrix` does not comp...,,2022-03-03T15:14:54Z,4.3,"[""astropy/modeling/tests/test_separable.py::te...","[""astropy/modeling/tests/test_separable.py::te...",298ccb478e6bf092953bca67a3d29dc6c35f6752,15 min - 1 hour
1,astropy/astropy,astropy__astropy-13033,298ccb478e6bf092953bca67a3d29dc6c35f6752,diff --git a/astropy/timeseries/core.py b/astr...,diff --git a/astropy/timeseries/tests/test_sam...,TimeSeries: misleading exception when required...,The relevant code that produces the misleading...,2022-03-31T23:28:27Z,4.3,"[""astropy/timeseries/tests/test_sampled.py::te...","[""astropy/timeseries/tests/test_sampled.py::te...",298ccb478e6bf092953bca67a3d29dc6c35f6752,15 min - 1 hour
2,astropy/astropy,astropy__astropy-13236,6ed769d58d89380ebaa1ef52b300691eefda8928,diff --git a/astropy/table/table.py b/astropy/...,diff --git a/astropy/table/tests/test_mixin.py...,Consider removing auto-transform of structured...,@mhvk - I'm happy to do this PR if you think i...,2022-05-09T14:16:30Z,5.0,"[""astropy/table/tests/test_mixin.py::test_ndar...","[""astropy/table/tests/test_mixin.py::test_attr...",cdf311e0714e611d48b0a31eb1f0e2cbffab7f23,15 min - 1 hour
3,astropy/astropy,astropy__astropy-13398,6500928dc0e57be8f06d1162eacc3ba5e2eff692,diff --git a/astropy/coordinates/builtin_frame...,diff --git a/astropy/coordinates/tests/test_in...,A direct approach to ITRS to Observed transfor...,"cc @StuartLittlefair, @adrn, @eteq, @eerovaher...",2022-06-24T15:22:11Z,5.0,"[""astropy/coordinates/tests/test_intermediate_...","[""astropy/coordinates/tests/test_intermediate_...",cdf311e0714e611d48b0a31eb1f0e2cbffab7f23,1-4 hours
4,astropy/astropy,astropy__astropy-13453,19cc80471739bcb67b7e8099246b391c355023ee,diff --git a/astropy/io/ascii/html.py b/astrop...,diff --git a/astropy/io/ascii/tests/test_html....,ASCII table output to HTML does not support su...,Welcome to Astropy 👋 and thank you for your fi...,2022-07-14T10:04:40Z,5.0,"[""astropy/io/ascii/tests/test_html.py::test_wr...","[""astropy/io/ascii/tests/test_html.py::test_li...",cdf311e0714e611d48b0a31eb1f0e2cbffab7f23,15 min - 1 hour

In [ ]:
df.types()

In [4]:
df_eval = pd.read_parquet("../data/raw/agentless_claude35sonnet_labels.parquet")

df_eval.head()

              instance_id         status  resolved
0  astropy__astropy-12907       resolved      True
1  astropy__astropy-13453       resolved      True
2  astropy__astropy-13579  no_generation     False
3  astropy__astropy-14096       resolved      True
4  astropy__astropy-14309       resolved      True

In [6]:
df["patch"][0]

"diff --git a/astropy/modeling/separable.py b/astropy/modeling/separable.py\n--- a/astropy/modeling/separable.py\n+++ b/astropy/modeling/separable.py\n@@ -242,7 +242,7 @@ def _cstack(left, right):\n         cright = _coord_matrix(right, 'right', noutp)\n     else:\n         cright = np.zeros((noutp, right.shape[1]))\n-        cright[-right.shape[0]:, -right.shape[1]:] = 1\n+        cright[-right.shape[0]:, -right.shape[1]:] = right\n \n     return np.hstack([cleft, cright])\n \n"

In [ ]:
df_eval = pd.read_parquet("../results/result.parquet")

In [ ]:
df_eval.head()